# Generated by Django 3.2.13 on 2022-05-04 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBefore',
            fields=[
                ('ProID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Unapprove', max_length=100)),
                ('projectname', models.CharField(max_length=150)),
                ('projectmanager', models.CharField(max_length=150)),
                ('article', models.CharField(max_length=1500)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('PreStudentID', models.ManyToManyField(blank=True, related_name='PreStudentID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAfter',
            fields=[
                ('ProID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='OnGoing', max_length=100)),
                ('projectname', models.CharField(max_length=150)),
                ('projectmanager', models.CharField(max_length=150)),
                ('article', models.CharField(max_length=1500)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('StudentID', models.ManyToManyField(blank=True, related_name='StudentID', to=settings.AUTH_USER_MODEL)),
                ('TeacherID', models.ManyToManyField(blank=True, related_name='TeacherID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
                ('projectcommented', models.ManyToManyField(blank=True, related_name='projectcommented', to='project.ProjectAfter')),
            ],
        ),
    ]
